### ISSUE TITLE
Set Up React-Router

### ISSUE THREAD

**Issue by lmosele** [EmmonsVentures/projectsuccotash#5]
Setting up react-router to make our SPA a bit easier to implement

@EmmonsVentures Should we made the login page a separate, normal static website for SEO purposes?

**Comment by EmmonsVentures** [comment]
@lmosele That might be a good idea.  Also, I found some boilerplate for a redux/ react/ firebase app with auth and it has react-router set up and provides a good starting point for our stack.  I'm out at the moment, but I can get up to the repo in a little while if that's something you're open to.

**Comment by lmosele** [comment]
@EmmonsVentures yeah that sounds great! lets take a look at it via PR and discuss

**Comment by EmmonsVentures** [comment]
Okay sounds good. I'll be back online in a few hours and can discuss then
